name: Check links

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'CHANGELOG.md'
  push:
    branches: ['7.x']
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'CHANGELOG.md'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  links:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: "--verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'"
          output: ${{ runner.temp }}/lychee/out.md
          format: markdown
          jobSummary: true
          fail: true
